language: cpp
os: linux
dist: xenial

services:
  - docker

before_install:
  #- docker pull trinhpham/xiaomi-r3g-openwrt-builder
  - docker build -t marcoavesani/openwrt_image_build_rm2100 .

before_script: chmod 777 /src -r


script:
  - docker run -t -e GITHUB_TOKEN=$GITHUB_TOKEN -e GIT_REPO=$TRAVIS_REPO_SLUG marcoavesani/openwrt_image_build_rm2100
  
branches:
  only:
  - master
